name: Eitaa Morning Message

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  send-morning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Check required files
        run: |
          echo "Checking files..."

          test -f morning_sender.py
          test -f morning_messages.json

          test -f "مرحله_۱_۳۰۰_متن_فرزندپروری_و_روانشناسی_کودک.txt"

          test -f "200_poems_children_shokoofehaye_mahdavi.txt"

          test -f "300_texts_parenting_children.txt"

          echo "✅ All files found."

      - name: Send Eitaa messages
        env:
          EITAA_TOKEN: ${{ secrets.EITAA_TOKEN }}
        run: python morning_sender.py
