name: Eitaa Morning Message

on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  send-morning:
    runs-on: ubuntu-latest

    steps:
      - name: Download files
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Send morning message
        env:
          EITAA_TOKEN: ${{ secrets.EITAA_TOKEN }}
        run: python morning_sender.py
